name: apptemplate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  bloc:
  build_runner:

  cupertino_icons: ^1.0.8
  dartz:
  dio:
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_multi_formatter:
  firebase_messaging:
  flutter_local_notifications: 
  flutter_native_splash:
  flutter_svg:
  get_it:
  go_router:
  google_fonts:
  hive:
  hive_flutter:
  path:
  pretty_dio_logger:


dev_dependencies:
  flutter_launcher_icons:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator:
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/

